# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EdsCountry.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(646, 518)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.CountryLabel = QtWidgets.QLabel(self.centralwidget)
        self.CountryLabel.setGeometry(QtCore.QRect(12, 12, 191, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CountryLabel.setFont(font)
        self.CountryLabel.setObjectName("CountryLabel")
        self.CountryNameLabel = QtWidgets.QLabel(self.centralwidget)
        self.CountryNameLabel.setGeometry(QtCore.QRect(210, 40, 371, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.CountryNameLabel.setFont(font)
        self.CountryNameLabel.setObjectName("CountryNameLabel")
        self.CountryFlagLabel = QtWidgets.QLabel(self.centralwidget)
        self.CountryFlagLabel.setGeometry(QtCore.QRect(210, 70, 240, 170))
        self.CountryFlagLabel.setText("")
        self.CountryFlagLabel.setObjectName("CountryFlagLabel")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(203, 260, 81, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(203, 288, 94, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(203, 403, 229, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.KMilecomboBox = QtWidgets.QComboBox(self.centralwidget)
        self.KMilecomboBox.setGeometry(QtCore.QRect(303, 288, 66, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.KMilecomboBox.setFont(font)
        self.KMilecomboBox.setObjectName("KMilecomboBox")
        self.KMilecomboBox.addItem("")
        self.KMilecomboBox.addItem("")
        self.labelTotalArea = QtWidgets.QLabel(self.centralwidget)
        self.labelTotalArea.setGeometry(QtCore.QRect(375, 288, 131, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelTotalArea.setFont(font)
        self.labelTotalArea.setObjectName("labelTotalArea")
        self.labelPopDens = QtWidgets.QLabel(self.centralwidget)
        self.labelPopDens.setGeometry(QtCore.QRect(350, 360, 121, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelPopDens.setFont(font)
        self.labelPopDens.setObjectName("labelPopDens")
        self.labelPerPop = QtWidgets.QLabel(self.centralwidget)
        self.labelPerPop.setGeometry(QtCore.QRect(438, 403, 50, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelPerPop.setFont(font)
        self.labelPerPop.setObjectName("labelPerPop")
        self.pushButtonUPDATE = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonUPDATE.setGeometry(QtCore.QRect(511, 348, 101, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonUPDATE.setFont(font)
        self.pushButtonUPDATE.setObjectName("pushButtonUPDATE")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(204, 319, 130, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.listWidgetCountry = QtWidgets.QListWidget(self.centralwidget)
        self.listWidgetCountry.setGeometry(QtCore.QRect(10, 40, 191, 391))
        self.listWidgetCountry.setObjectName("listWidgetCountry")
        self.radioButtonMile = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButtonMile.setGeometry(QtCore.QRect(204, 344, 133, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButtonMile.setFont(font)
        self.radioButtonMile.setChecked(False)
        self.radioButtonMile.setAutoExclusive(False)
        self.radioButtonMile.setObjectName("radioButtonMile")
        self.radioButtonKM = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButtonKM.setGeometry(QtCore.QRect(204, 373, 126, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButtonKM.setFont(font)
        self.radioButtonKM.setObjectName("radioButtonKM")
        self.lineEditPop = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditPop.setGeometry(QtCore.QRect(290, 260, 133, 20))
        self.lineEditPop.setObjectName("lineEditPop")
        self.CountryLabel.raise_()
        self.CountryNameLabel.raise_()
        self.CountryFlagLabel.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_4.raise_()
        self.KMilecomboBox.raise_()
        self.labelTotalArea.raise_()
        self.labelPopDens.raise_()
        self.labelPerPop.raise_()
        self.label_3.raise_()
        self.pushButtonUPDATE.raise_()
        self.listWidgetCountry.raise_()
        self.radioButtonMile.raise_()
        self.radioButtonKM.raise_()
        self.lineEditPop.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 646, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.actionLoad_Countries = QtWidgets.QAction(MainWindow)
        self.actionLoad_Countries.setObjectName("actionLoad_Countries")
        self.actionSave_to_Files = QtWidgets.QAction(MainWindow)
        self.actionSave_to_Files.setObjectName("actionSave_to_Files")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Edward\'s Country Application"))
        self.CountryLabel.setText(_translate("MainWindow", "Choose a Country From the List"))
        self.CountryNameLabel.setText(_translate("MainWindow", "Country Name"))
        self.label.setText(_translate("MainWindow", "Population:"))
        self.label_2.setText(_translate("MainWindow", "Total Area In"))
        self.label_4.setText(_translate("MainWindow", "Percentage of World Population:"))
        self.KMilecomboBox.setItemText(0, _translate("MainWindow", "Sq. Mi"))
        self.KMilecomboBox.setItemText(1, _translate("MainWindow", "Sq. KM"))
        self.labelTotalArea.setText(_translate("MainWindow", "TotalArea"))
        self.labelPopDens.setText(_translate("MainWindow", "PopDens"))
        self.labelPerPop.setText(_translate("MainWindow", "PerPop"))
        self.pushButtonUPDATE.setText(_translate("MainWindow", "Update"))
        self.label_3.setText(_translate("MainWindow", "Population density"))
        self.radioButtonMile.setText(_translate("MainWindow", "Per Square Mile"))
        self.radioButtonKM.setText(_translate("MainWindow", "Per Square KM"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionLoad_Countries.setText(_translate("MainWindow", "Load Countries"))
        self.actionSave_to_Files.setText(_translate("MainWindow", "Save to Files"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

